### PR TITLE
packages version update 

### PR DESCRIPTION
**Pull request by eugenejeonme**
1. cloud_firebase : 2.0.0 -> 2.2.1
2. shared_preferences : 2.0.0 -> 2.0.6
3. build_runner : 2.0.0 -> 2.0.4
4. mocktail : 0.1.2 -> 0.1.4

### CODE REVIEW

**Comment by zeshuaro** [comment]
Thanks for your contribution but would you be able to explain why are these changes required? 

I just tested myself with an application using `cloud_firestore: ^2.2.1` and `firestore_cache` and I didn't see any dependency conflict issues.

PS This repository is configured with [Renovate](https://renovatebot.com/) which will update the dependencies automatically if they're out-of-date.

**Comment by AathifMahir** [comment]
> Thanks for your contribution but would you be able to explain why are these changes required? 
> 
> 
> 
> I just tested myself with an application using `cloud_firestore: ^2.2.1` and `firestore_cache` and I didn't see any dependency conflict issues.
> 
> 
> 
> PS This repository is configured with [Renovate](https://renovatebot.com/) which will update the dependencies automatically if they're out-of-date.

I also tested, I don't find a dependency conflict with the current version, still won't mind upgrading.

@zeshuaro you decide, what do on this pull request.

**Comment by eugenejeonme** [comment]
> Thanks for your contribution but would you be able to explain why are these changes required?
> 
> I just tested myself with an application using `cloud_firestore: ^2.2.1` and `firestore_cache` and I didn't see any dependency conflict issues.
> 
> PS This repository is configured with [Renovate](https://renovatebot.com/) which will update the dependencies automatically if they're out-of-date.

I liked this project so much, I wanted to use it in my product.
But I just wanted to ask for an upgrade because my version did not match my product already.

And I just learned the information [Renovate] (https://renovatebot.com/) I learn a lot from your project, thank you so much. :)

**Comment by zeshuaro** [comment]
@eugenejeonme What version of `cloud_firestore` are you using and what errors are you seeing?

**Comment by eugenejeonme** [comment]
> @eugenejeonme What version of `cloud_firestore` are you using? Or are there other issues with another dependency?
> 
> And what errors are you seeing?

1. cloud_firebase: ^2.2.1
2. build_runner: ^2.0.4


I am using the above version. And I'm just using the latest version - there's no error. :)
I also understood that the version was automatically updated.

So, You decide. You can close it.

**Comment by zeshuaro** [comment]
If you're not currently experiencing any issues I'll prefer to leave it as is and to avoid releasing a new version. `build_runner` is a `devDependency` so it won't affect your project anyway. Feel free to open an issue or PR if there's any versioning issues with the dependencies. 🙂

**Pull request closed without merging**
